# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  # port forward sample
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  #config.vm.network "forwarded_port", guest: 88, host: 88, protocol: "udp"
  username = "#{ENV['USERNAME'] || `whoami`}"
  config.vm.synced_folder "/home/#{username}/_prj/", "/home/vagrant/_prj/", type: "virtualbox"
  config.vm.provision "shell", path: "script.sh"
end
